[package]
name = "rheaps"
version = "0.16.0"
edition = "2024"
rust-version = "1.88"
description = "Heap data structures for Rust"
license = "Apache-2.0"
repository = "https://github.com/d-michail/rheaps"
documentation = "https://docs.rs/rheaps"
readme = "README.md"
keywords = ["heap", "priority-queue", "data-structures"]
categories = ["data-structures"]

[dependencies]
num-bigint = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1"

[features]
serde = ["dep:serde", "num-bigint/serde"]
